micronaut:
  application:
    name: demo1
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
#    schema-generate: CREATE_DROP
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
